title: Developer Notes
author: Adyg
description: > 
  Small collection of notes about interesting things I run into while working on web apps.
twitter_username: adriang
github_username:  adyg
stackoverflow_username: adrian-ghiuta
stackoverflow_id: 4769900
stackoverflow_name: adriang

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - vagrant
  - run_dev_server.sh