- hosts: all

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.ruby
    - geerlingguy.nodejs

  tasks:
    - name: Running bundle install
      when: bundler_gemfile_path is defined
      command: bundle install --gemfile {{ bundler_gemfile_path }}
      sudo: no